[connections.snowflake]
account = "KUMEOTP.NT78323"
user = "JoanaRequeijo"
password = "JgOADgv0vg5YPKfT74aMx4bZqEcjI4tTJ1Po4s2sAhtQgD"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
