[connections.snowflake]
account = "KUMEOTP-NT78323"
user = "JoanaRequeijo"
password = ""
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
