[connections.snowflake]
account = "KUMEOTP.NT78323"
user = "joana_r91@hotmail.com"
password = "NoivinhO13!Snow"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
